[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["tex <texhnolainx@gmail.com>"]
description = "My first wasm project!"
license = "MIT/Apache-2.0"
repository = "https://github.com/texhno/hello-wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"